name: Production Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: ğŸ‘©â€ğŸ”¬ Deployment
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIA4PUCVHFXPAKCHKPG
      AWS_SECRET_ACCESS_KEY: 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
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: âš™ï¸ PNPM Install
        run: pnpm i
      - name: ğŸ§¹ Lint
        run: pnpm lint
      - name: ğŸ¥ Build Frontend
        run: pnpm build:web
      - name: ğŸ Build Backend
        run: pnpm build:backend
      - name: ğŸ§ª Test
        run: pnpm test:prod
      - name: ğŸ±â€ğŸ’» Deploy
        run: pnpm deploy:prod
      - name: ğŸ‡ Notify
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
